spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=emarket
    username: postgres
    password: password
  flyway:
    enabled: true
    validate-on-migrate: true
    clean-on-validation-error: true
    default-schema: emarket



server:
  port: 8082